version: 2.1
orbs:
  python: circleci/python@2.1.1
executors:
  node:
    docker:
      - image: cimg/node:20.11
    working_directory: ~/kostianis-web


jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - run: 
          name: Give permissions
          command: chmod -R 777 build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy-staging:
    executor: python/default
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to Staging FTP
          command: |
            cd /workspace/build
            # Replace with your FTP upload script
            # lftp -u $FTP_USER,$FTP_PASS -e "mirror -R ./ /path/to/staging/server/; quit" $FTP_HOST
            echo "Deploying to Staging FTP..."

  deploy-production:
    executor: python/default
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to Production FTP
          command: |
            cd /workspace/build
            # Replace with your FTP upload script
            # lftp -u $FTP_USER,$FTP_PASS -e "mirror -R ./ /path/to/production/server/; quit" $FTP_HOST
            echo "Deploying to Production FTP..."

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              ignore: main
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: main
